Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2019-07, with the labels that each got.

#318 [7.4.x][KIECLOUD-122] Adjust Kie Server immutable AMQ template to anble JMS client configur…
  templates/rhpam74-prod-immutable-kieserver-amq.yaml
Labels: 7.4.x ⇨ 7.4.0, on hold ⏳

#321 [KIECLOUD-122]Adjust Kie Server immutable AMQ template to anble JMS c…
  templates/rhpam75-prod-immutable-kieserver-amq.yaml
Labels: master ⇨ 7.5.0, on hold ⏳

#322 [RHPAM-2232] Remove businesscentral-indexing image and reference in s…
  README.md
  businesscentral-indexing/branch-overrides.yaml
  businesscentral-indexing/container.yaml
  businesscentral-indexing/content_sets.yml
  businesscentral-indexing/image.yaml
  businesscentral-indexing/tag-overrides.yaml
  businesscentral/image.yaml
  ce.yaml
  rhpam74-image-streams.yaml
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#323 [RHPAM-2232] Remove businesscentral-indexing image and reference in streams
  README.md
  businesscentral-indexing/branch-overrides.yaml
  businesscentral-indexing/container.yaml
  businesscentral-indexing/content_sets.yml
  businesscentral-indexing/image.yaml
  businesscentral-indexing/tag-overrides.yaml
  businesscentral/image.yaml
  ce.yaml
  rhpam75-image-streams.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#324 KIECLOUD-271: corrected default parameter description for nonXA DS
  templates/rhpam75-kieserver-externaldb.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#327 KIECLOUD-271: corrected default parameter description for nonXA DS (#…
  templates/rhpam74-kieserver-externaldb.yaml
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#328 RHPAM-2252 Move kie-server-id annotation to Kie server DC in managed …
  templates/rhpam75-managed.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#329 [7.4.x] RHPAM-2252 Move kie-server-id annotation to Kie server DC in managed …
  templates/rhpam74-managed.yaml
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#331 [RHPAM-2254]Add Missing env variables to prod OpenShift template
  templates/rhpam75-prod.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#332 [7.4.x][RHPAM-2254]Add Missing env variables to prod OpenShift template
  templates/rhpam74-prod.yaml
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#330 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  templates/rhpam75-prod-immutable-monitor.yaml
  templates/rhpam75-prod.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#334 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  templates/rhpam74-prod-immutable-monitor.yaml
  templates/rhpam74-prod.yaml
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#333 [KIECLOUD-266] - Update MSSQL jdbc driver on jdbc extensions images.
  templates/contrib/jdbc/README.md
  templates/contrib/jdbc/prepare.sh
Labels: master ⇨ 7.5.0, ready 🚀

#335 [KIECLOUD-266] - Update MSSQL jdbc driver on jdbc extensions images.
  templates/contrib/jdbc/README.md
  templates/contrib/jdbc/prepare.sh
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#337 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  templates/rhpam74-prod-immutable-monitor.yaml
  templates/rhpam74-prod.yaml
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#338 [RHPAM-1387] - Allow set Smart router location to external URL in RHPAM
  templates/rhpam75-prod-immutable-monitor.yaml
  templates/rhpam75-prod.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#336 [KIECLOUD-268] - Update RHPAM and RHMD templates and imagestreams on …
  templates/docs/rhpam74-kieserver-externaldb.adoc
  templates/docs/rhpam74-kieserver-mysql.adoc
  templates/docs/rhpam74-kieserver-postgresql.adoc
  templates/docs/rhpam74-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam74-prod-immutable-monitor.adoc
  templates/docs/rhpam74-prod.adoc
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#339 [KIECLOUD-268] - Update RHPAM and RHMD templates and imagestreams on …
  templates/docs/rhpam74-authoring-ha.adoc
  templates/docs/rhpam74-authoring.adoc
  templates/docs/rhpam74-kieserver-externaldb.adoc
  templates/docs/rhpam74-kieserver-mysql.adoc
  templates/docs/rhpam74-kieserver-postgresql.adoc
  templates/docs/rhpam74-managed.adoc
  templates/docs/rhpam74-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam74-prod-immutable-kieserver.adoc
  templates/docs/rhpam74-prod-immutable-monitor.adoc
  templates/docs/rhpam74-prod.adoc
  templates/docs/rhpam74-trial-ephemeral.adoc
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#341 [KIECLOUD-277] - JMS Parameters available for user toc onfigure but n…
  templates/rhpam75-prod-immutable-kieserver-amq.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#340 [KIECLOUD-277] - JMS Parameters available for user toc onfigure but n…
  templates/rhpam74-prod-immutable-kieserver-amq.yaml
Labels: 7.4.x ⇨ 7.4.1, ready 🚀

#343 [KIECLOUD-290] bump 7.4 versions to 7.4.1
  businesscentral-monitoring/image.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/image.yaml
  businesscentral/tag-overrides.yaml
  controller/image.yaml
  controller/tag-overrides.yaml
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  rhpam74-image-streams.yaml
  smartrouter/image.yaml
  smartrouter/tag-overrides.yaml
  templates/docs/README.adoc
  templates/docs/rhpam74-authoring-ha.adoc
  templates/docs/rhpam74-authoring.adoc
  templates/docs/rhpam74-kieserver-externaldb.adoc
  templates/docs/rhpam74-kieserver-mysql.adoc
  templates/docs/rhpam74-kieserver-postgresql.adoc
  templates/docs/rhpam74-managed.adoc
  templates/docs/rhpam74-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam74-prod-immutable-kieserver.adoc
  templates/docs/rhpam74-prod-immutable-monitor.adoc
  templates/docs/rhpam74-prod.adoc
  templates/docs/rhpam74-trial-ephemeral.adoc
  templates/rhpam74-authoring-ha.yaml
  templates/rhpam74-authoring.yaml
  templates/rhpam74-kieserver-externaldb.yaml
  templates/rhpam74-kieserver-mysql.yaml
  templates/rhpam74-kieserver-postgresql.yaml
  templates/rhpam74-managed.yaml
  templates/rhpam74-prod-immutable-kieserver-amq.yaml
  templates/rhpam74-prod-immutable-kieserver.yaml
  templates/rhpam74-prod-immutable-monitor.yaml
  templates/rhpam74-prod.yaml
  templates/rhpam74-trial-ephemeral.yaml
Labels: 7.4.x ⇨ 7.4.1, ready 🚀

#344 [KIECLOUD-290] bump 7.4 versions to 7.4.1
  templates/docs/README.adoc
  templates/docs/rhpam74-kieserver-externaldb.adoc
  templates/docs/rhpam74-kieserver-mysql.adoc
  templates/docs/rhpam74-kieserver-postgresql.adoc
  templates/docs/rhpam74-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam74-prod-immutable-kieserver.adoc
  templates/docs/rhpam74-prod.adoc
  templates/docs/rhpam74-trial-ephemeral.adoc
Labels: 7.4.x ⇨ 7.4.1, ready 🚀

#345 [KIECLOUD-291] bring adoc generation fixes from 7.4.1 to 7.5.0
  templates/docs/README.adoc
  templates/docs/rhpam75-authoring-ha.adoc
  templates/docs/rhpam75-authoring.adoc
  templates/docs/rhpam75-kieserver-externaldb.adoc
  templates/docs/rhpam75-kieserver-mysql.adoc
  templates/docs/rhpam75-kieserver-postgresql.adoc
  templates/docs/rhpam75-managed.adoc
  templates/docs/rhpam75-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam75-prod-immutable-kieserver.adoc
  templates/docs/rhpam75-prod-immutable-monitor.adoc
  templates/docs/rhpam75-prod.adoc
  templates/docs/rhpam75-trial-ephemeral.adoc
Labels: master ⇨ 7.5.0, ready 🚀
