Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2019-06, with the labels that each got.

#310 [KIECLOUD-232] - Update images of "amq-broker" to version 7.3
  templates/docs/rhpam74-authoring-ha.adoc
  templates/rhpam74-authoring-ha.yaml
  templates/rhpam74-prod-immutable-kieserver-amq.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#312 [KIECLOUD-97] Synchronize OpenShiftStartupStrategy related changes between Template, APB, and Operator
  templates/rhpam74-authoring-ha.yaml
  templates/rhpam74-authoring.yaml
  templates/rhpam74-kieserver-externaldb.yaml
  templates/rhpam74-kieserver-mysql.yaml
  templates/rhpam74-kieserver-postgresql.yaml
  templates/rhpam74-managed.yaml
  templates/rhpam74-prod-immutable-kieserver-amq.yaml
  templates/rhpam74-prod-immutable-kieserver.yaml
  templates/rhpam74-prod-immutable-monitor.yaml
  templates/rhpam74-trial-ephemeral.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#315 [RHPAM-2016] fix osbs repo branch suffix per clarified release guidelines
  businesscentral-indexing/image.yaml
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  kieserver/image.yaml
  smartrouter/image.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#316 [RHPAM-2016] fix osbs repo branch suffix per clarified release guidelines
  businesscentral-indexing/image.yaml
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  kieserver/image.yaml
  smartrouter/image.yaml
Labels: master ⇨ 7.4.0, ready 🚀

#319 [RHPAM-2226] Validation subelement is missing for datasources
  templates/rhpam74-kieserver-mysql.yaml
  templates/rhpam74-kieserver-postgresql.yaml
Labels: 7.4.x ⇨ 7.4.0, ready 🚀

#320 [RHPAM-2226] Validation subelement is missing for datasources
  templates/rhpam75-kieserver-mysql.yaml
  templates/rhpam75-kieserver-postgresql.yaml
Labels: master ⇨ 7.5.0, ready 🚀
