Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2019-09, with the labels that each got.

#358 [RHPAM-2279] - Review and update Authoring HA template for latest cha…
  templates/rhpam75-authoring-ha.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#356 [KIECLOUD-313] upgrade EAP from 7.2.1 to 7.2.3
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/branch-overrides.yaml
  controller/image.yaml
  controller/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#357 [RHPAM-2354] OutOfMemoryError on Datagrid cause issues on project import indexing
  templates/rhpam75-authoring-ha.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#360 Update AMQ image version for kieserver jms integration
  templates/rhpam75-prod-immutable-kieserver-amq.yaml
Labels: master ⇨ 7.5.0, ready 🚀

#361 [BXMSDOC-4566] Misha's editorial changes for 7.5 - 7.5.x branch
  templates/rhpam75-authoring-ha.yaml
  templates/rhpam75-authoring.yaml
  templates/rhpam75-kieserver-externaldb.yaml
  templates/rhpam75-kieserver-mysql.yaml
  templates/rhpam75-kieserver-postgresql.yaml
  templates/rhpam75-managed.yaml
  templates/rhpam75-prod-immutable-kieserver-amq.yaml
  templates/rhpam75-prod-immutable-kieserver.yaml
  templates/rhpam75-prod-immutable-monitor.yaml
  templates/rhpam75-prod.yaml
  templates/rhpam75-trial-ephemeral.yaml
Labels: 7.5.x ⇨ 7.5.0, ready 🚀

#359 [BXMSDOC-4566] Misha's editorial changes for 7.5
  templates/rhpam76-authoring-ha.yaml
  templates/rhpam76-authoring.yaml
  templates/rhpam76-kieserver-externaldb.yaml
  templates/rhpam76-kieserver-mysql.yaml
  templates/rhpam76-kieserver-postgresql.yaml
  templates/rhpam76-managed.yaml
  templates/rhpam76-prod-immutable-kieserver-amq.yaml
  templates/rhpam76-prod-immutable-kieserver.yaml
  templates/rhpam76-prod-immutable-monitor.yaml
  templates/rhpam76-prod.yaml
  templates/rhpam76-trial-ephemeral.yaml
Labels: master ⇨ 7.6.0, ready 🚀

#362 regen adocs for 7.5.0
  templates/docs/rhpam75-authoring-ha.adoc
  templates/docs/rhpam75-authoring.adoc
  templates/docs/rhpam75-kieserver-externaldb.adoc
  templates/docs/rhpam75-kieserver-mysql.adoc
  templates/docs/rhpam75-kieserver-postgresql.adoc
  templates/docs/rhpam75-managed.adoc
  templates/docs/rhpam75-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam75-prod-immutable-kieserver.adoc
  templates/docs/rhpam75-prod-immutable-monitor.adoc
  templates/docs/rhpam75-prod.adoc
  templates/docs/rhpam75-trial-ephemeral.adoc
Labels: 7.5.x ⇨ 7.5.0, ready 🚀

#363 regen adocs for 7.6.0
  templates/docs/rhpam76-authoring-ha.adoc
  templates/docs/rhpam76-authoring.adoc
  templates/docs/rhpam76-kieserver-externaldb.adoc
  templates/docs/rhpam76-kieserver-mysql.adoc
  templates/docs/rhpam76-kieserver-postgresql.adoc
  templates/docs/rhpam76-managed.adoc
  templates/docs/rhpam76-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam76-prod-immutable-kieserver.adoc
  templates/docs/rhpam76-prod-immutable-monitor.adoc
  templates/docs/rhpam76-prod.adoc
  templates/docs/rhpam76-trial-ephemeral.adoc
Labels: master ⇨ 7.6.0, ready 🚀

#351 [RHPAM-2311] Add openshift module for proces-migration
  process-migration/README.adoc
  process-migration/branch-overrides.yaml
  process-migration/container.yaml
  process-migration/content_sets.yml
  process-migration/image.yaml
  process-migration/tag-overrides.yaml
Labels: master ⇨ 7.6.0, ready 🚀

#365 KIECLOUD-324-7.5.x] - inform latest supported/tested cekit version
  templates/contrib/jdbc/README.md
Labels: 7.5.x ⇨ 7.5.0

#368 [ADOCS_REGEN] regenerate adocs per recent changes
  templates/docs/rhpam75-kieserver-mysql.adoc
  templates/docs/rhpam75-kieserver-postgresql.adoc
  templates/docs/rhpam75-trial-ephemeral.adoc
Labels: 7.5.x ⇨ 7.5.0, ready 🚀
