Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2020-10, with the labels that each got.

#470 [KIECLOUD-441] - Prepare RHPAM and RHDM repositories for 7.9.0 release
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral/branch-overrides.yaml
  controller/branch-overrides.yaml
  kieserver/branch-overrides.yaml
  process-migration/branch-overrides.yaml
  smartrouter/branch-overrides.yaml
  templates/docs/README.adoc
  templates/docs/rhpam79-authoring-ha.adoc
  templates/docs/rhpam79-authoring.adoc
  templates/docs/rhpam79-kieserver-externaldb.adoc
  templates/docs/rhpam79-kieserver-mysql.adoc
  templates/docs/rhpam79-kieserver-postgresql.adoc
  templates/docs/rhpam79-managed.adoc
  templates/docs/rhpam79-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam79-prod-immutable-kieserver.adoc
  templates/docs/rhpam79-prod-immutable-monitor.adoc
  templates/docs/rhpam79-prod.adoc
  templates/docs/rhpam79-trial-ephemeral.adoc
Labels: 7.9.x ⇨ 7.9.0, needs review :mag:

#472 [KIECLOUD-451] - Update txn-recovery-marker and update EAP 7.3.2 tag …
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: needs review :mag:

#474 [BXMSDOC-6663] Editorial change - add comma
  templates/rhpam710-authoring-ha.yaml
  templates/rhpam710-authoring.yaml
  templates/rhpam710-kieserver-externaldb.yaml
  templates/rhpam710-kieserver-mysql.yaml
  templates/rhpam710-kieserver-postgresql.yaml
  templates/rhpam710-managed.yaml
  templates/rhpam710-prod-immutable-kieserver-amq.yaml
  templates/rhpam710-prod-immutable-kieserver.yaml
  templates/rhpam710-prod-immutable-monitor.yaml
  templates/rhpam710-prod.yaml
  templates/rhpam710-trial-ephemeral.yaml
Labels: master ⇨ 7.10.0, ready 🚀

#475 [BXMSDOC-6663] Editorial change - add comma
  templates/rhpam79-authoring-ha.yaml
  templates/rhpam79-authoring.yaml
  templates/rhpam79-kieserver-externaldb.yaml
  templates/rhpam79-kieserver-mysql.yaml
  templates/rhpam79-kieserver-postgresql.yaml
  templates/rhpam79-managed.yaml
  templates/rhpam79-prod-immutable-kieserver-amq.yaml
  templates/rhpam79-prod-immutable-kieserver.yaml
  templates/rhpam79-prod-immutable-monitor.yaml
  templates/rhpam79-prod.yaml
  templates/rhpam79-trial-ephemeral.yaml
Labels: 7.9.x ⇨ 7.9.0, master ⇨ 7.10.0
