Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2020-01, with the labels that each got.

#405 update adocs
  templates/docs/rhpam76-authoring-ha.adoc
Labels: 7.6.x ⇨ 7.6.0

#406 [KIECLOUD-352] - Smartrouter is not honoring JAVA_OPTS_APPEND and dyn…
  smartrouter/image.yaml
Labels: master ⇨ 7.7.0

#403 [RHPAM-2608] Increase DataGrid 7.3 image tag version to 1.4 in OpenShift templates
  templates/rhpam77-authoring-ha.yaml
Labels: master ⇨ 7.7.0, ready 🚀

#408 [KIECLOUD-355] Upgrade RHDM and RHPAM EAP-based images to EAP 7.2.6
  businesscentral-monitoring/artifact-overrides.yaml
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/artifact-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/artifact-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  kieserver/artifact-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: master ⇨ 7.7.0, ready 🚀

#410 [RHPAM-2175] Use only adminUser from a credentials secret
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  example-credentials.yaml
  kieserver/image.yaml
  smartrouter/image.yaml
  templates/rhpam77-authoring-ha.yaml
  templates/rhpam77-authoring.yaml
  templates/rhpam77-kieserver-externaldb.yaml
  templates/rhpam77-kieserver-mysql.yaml
  templates/rhpam77-kieserver-postgresql.yaml
  templates/rhpam77-managed.yaml
  templates/rhpam77-prod-immutable-kieserver-amq.yaml
  templates/rhpam77-prod-immutable-kieserver.yaml
  templates/rhpam77-prod-immutable-monitor.yaml
  templates/rhpam77-prod.yaml
  templates/rhpam77-trial-ephemeral.yaml
Labels: master ⇨ 7.7.0, ready 🚀

#392 [RHPAM-2175] Add variable to image.yaml file
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  kieserver/image.yaml
  templates/rhpam77-authoring-ha.yaml
  templates/rhpam77-authoring.yaml
  templates/rhpam77-kieserver-externaldb.yaml
  templates/rhpam77-kieserver-mysql.yaml
  templates/rhpam77-kieserver-postgresql.yaml
  templates/rhpam77-managed.yaml
  templates/rhpam77-prod-immutable-kieserver-amq.yaml
  templates/rhpam77-prod-immutable-kieserver.yaml
  templates/rhpam77-prod-immutable-monitor.yaml
  templates/rhpam77-prod.yaml
  templates/rhpam77-trial-ephemeral.yaml
Labels: master ⇨ 7.7.0, ready 🚀
