Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2020-11, with the labels that each got.

#480 Add Kaitou to default reviewers
  .github/bot-files/reviewers.yml
Labels: needs review :mag:

#478 [RHPAM-3245] - Change resource requirements for BC and KIE Server
  templates/rhpam710-authoring-ha.yaml
  templates/rhpam710-authoring.yaml
  templates/rhpam710-kieserver-externaldb.yaml
  templates/rhpam710-kieserver-mysql.yaml
  templates/rhpam710-kieserver-postgresql.yaml
  templates/rhpam710-managed.yaml
  templates/rhpam710-prod-immutable-kieserver-amq.yaml
  templates/rhpam710-prod-immutable-kieserver.yaml
  templates/rhpam710-prod-immutable-monitor.yaml
  templates/rhpam710-prod.yaml
  templates/rhpam710-trial-ephemeral.yaml
Labels: needs review :mag:

#479 [RHPAM-3245-Cherrypick] - Change resource requirements for BC and KI…
  templates/rhpam79-authoring-ha.yaml
  templates/rhpam79-authoring.yaml
  templates/rhpam79-kieserver-externaldb.yaml
  templates/rhpam79-kieserver-mysql.yaml
  templates/rhpam79-kieserver-postgresql.yaml
  templates/rhpam79-managed.yaml
  templates/rhpam79-prod-immutable-kieserver-amq.yaml
  templates/rhpam79-prod-immutable-kieserver.yaml
  templates/rhpam79-prod-immutable-monitor.yaml
  templates/rhpam79-prod.yaml
  templates/rhpam79-trial-ephemeral.yaml
Labels: needs review :mag:

#477 [RHPAM-3273] Fix example for LOG_LEVEL in SmartRouter image
  smartrouter/image.yaml
Labels: master ⇨ 7.10.0, ready 🚀

#481 [RHPAM-3273] 7.9.x Fix example for LOG_LEVEL in SmartRouter image
  smartrouter/image.yaml
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#476 [AF-2626] - Create Dashbuilder Runtime Image
  .circleci/config.yml
  dashbuilder/README.adoc
  dashbuilder/artifact-overrides.yaml
  dashbuilder/branch-overrides.yaml
  dashbuilder/container.yaml
  dashbuilder/content_sets.yml
  dashbuilder/image.yaml
  dashbuilder/osbs-extra/gating.yaml
  dashbuilder/tag-overrides.yaml
Labels: ready 🚀

#485 [KIECLOUD-438] - DeploymentConfig probes for BusinessCentral too shor…
  templates/rhpam79-authoring-ha.yaml
  templates/rhpam79-authoring.yaml
  templates/rhpam79-managed.yaml
  templates/rhpam79-prod-immutable-monitor.yaml
  templates/rhpam79-prod.yaml
  templates/rhpam79-trial-ephemeral.yaml
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#484 [KIECLOUD-438] - DeploymentConfig probes for BusinessCentral too shor…
  templates/rhpam710-authoring-ha.yaml
  templates/rhpam710-authoring.yaml
  templates/rhpam710-managed.yaml
  templates/rhpam710-prod-immutable-monitor.yaml
  templates/rhpam710-prod.yaml
  templates/rhpam710-trial-ephemeral.yaml
Labels: master ⇨ 7.10.0, ready 🚀

#489 [AF-2626] - Create Dashbuilder Runtime Image
  dashbuilder/image.yaml
Labels: master ⇨ 7.10.0, needs review :mag:

#482 [RHPAM-3299] - BC image not using PV to store its local .m2/repository
  businesscentral/image.yaml
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#483 [RHPAM-3299] - BC image not using PV to store its local .m2/repository
  businesscentral/image.yaml
Labels: master ⇨ 7.10.0, ready 🚀

#488 [RHPAM-3300] - Add EJB timer related settings in OCP to avoid duplica…
  kieserver/image.yaml
Labels: master ⇨ 7.10.0, ready 🚀

#487 [RHPAM-3300] - Add EJB timer related settings in OCP to avoid duplica…
  kieserver/image.yaml
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#486 [RHPAM-3099] - Update EAP version from 7.3.3 on PAM/DM 7.9.x
  businesscentral-monitoring/artifact-overrides.yaml
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/artifact-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/artifact-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  kieserver/artifact-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: 7.9.x ⇨ 7.9.1, needs review :mag:

#490 [RHPAM-3099] - Update EAP version from 7.3.3 on PAM/DM 7.9.x
  businesscentral-monitoring/artifact-overrides.yaml
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/artifact-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/artifact-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  kieserver/artifact-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: master ⇨ 7.10.0, needs review :mag:

#492 [KIECLOUD-435] - Remove deprecated -released tags from image.yaml files
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  kieserver/image.yaml
  process-migration/image.yaml
  smartrouter/image.yaml
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#491 [KIECLOUD-435] - Remove deprecated -released tags from image.yaml files
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
  process-migration/image.yaml
  smartrouter/image.yaml
Labels: master ⇨ 7.10.0, needs review :mag:, ready 🚀

#495 [KIECLOUD-467] - Prepare RHDM and RHPAM 7.9.x branches for 7.9.1 release
  businesscentral-monitoring/image.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/image.yaml
  businesscentral/tag-overrides.yaml
  controller/image.yaml
  controller/tag-overrides.yaml
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  process-migration/image.yaml
  process-migration/tag-overrides.yaml
  quickstarts/router-ext/README.md
  rhpam79-image-streams.yaml
  smartrouter/image.yaml
  smartrouter/tag-overrides.yaml
  templates/contrib/jdbc/cekit/image.yaml
  templates/contrib/jdbc/cekit/modules/kie-custom-jdbc-driver/base-module.yaml
  templates/docs/rhpam79-authoring-ha.adoc
  templates/docs/rhpam79-authoring.adoc
  templates/docs/rhpam79-kieserver-externaldb.adoc
  templates/docs/rhpam79-kieserver-mysql.adoc
  templates/docs/rhpam79-kieserver-postgresql.adoc
  templates/docs/rhpam79-managed.adoc
  templates/docs/rhpam79-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam79-prod-immutable-kieserver.adoc
  templates/docs/rhpam79-prod-immutable-monitor.adoc
  templates/docs/rhpam79-prod.adoc
  templates/docs/rhpam79-trial-ephemeral.adoc
  templates/rhpam79-authoring-ha.yaml
  templates/rhpam79-authoring.yaml
  templates/rhpam79-kieserver-externaldb.yaml
  templates/rhpam79-kieserver-mysql.yaml
  templates/rhpam79-kieserver-postgresql.yaml
  templates/rhpam79-managed.yaml
  templates/rhpam79-prod-immutable-kieserver-amq.yaml
  templates/rhpam79-prod-immutable-kieserver.yaml
  templates/rhpam79-prod-immutable-monitor.yaml
  templates/rhpam79-prod.yaml
  templates/rhpam79-trial-ephemeral.yaml
Labels: 7.9.x ⇨ 7.9.1, needs review :mag:

#493 [KIECLOUD-466] - Avail the possibility to use the ubi8-mininal as bas…
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  kieserver/image.yaml
  smartrouter/image.yaml
Labels: master ⇨ 7.10.0, needs review :mag:
