Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2020-04, with the labels that each got.

#431 [KIECLOUD-378] - Increase AMQ broker version to 7.6
  templates/rhpam78-authoring-ha.yaml
  templates/rhpam78-prod-immutable-kieserver-amq.yaml
Labels: master ⇨ 7.8.0, ready 🚀

#430 [RHPAM-2724] - Increase DataGrid 7.3 image tag version to 1.5
  templates/rhpam77-authoring-ha.yaml
Labels: 7.7.x ⇨ 7.7, ready 🚀

#429 [RHPAM-2724] - Increase DataGrid 7.3 image tag version to 1.5
  templates/rhpam78-authoring-ha.yaml
Labels: master ⇨ 7.8.0, ready 🚀

#407 [RHPAM-2576] Set package manager
  process-migration/image.yaml
Labels: master ⇨ 7.8.0, ready 🚀

#428 RHPAM-2833: Allow to configure replicas in Authoring HA
  templates/docs/rhpam78-authoring-ha.adoc
  templates/rhpam78-authoring-ha.yaml
Labels: master ⇨ 7.8.0, ready 🚀

#437 [RHPAM-2830] BC and Kie Servers aren't syncronized
  templates/docs/rhpam78-authoring-ha.adoc
  templates/rhpam78-authoring-ha.yaml
Labels: master ⇨ 7.8.0, ready 🚀

#436 [RHPAM-2830] 7.7.x BC and Kie Servers aren't syncronized
  templates/docs/rhpam77-authoring-ha.adoc
  templates/rhpam77-authoring-ha.yaml
Labels: 7.7.x ⇨ 7.7.1, ready 🚀
