Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2021-12, with the labels that each got.

#579 [RHPAM-4064] BC HA does not start because of outdated configuration
  businesscentral/image.yaml
  templates/rhpam712-authoring-ha.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.0, needs-cherry-pick :cherries:

#580 [RHPAM-4064] BC HA does not start because of outdated configuration
  businesscentral/image.yaml
  templates/rhpam713-authoring-ha.yaml
Labels: ready 🚀, main ⇨ 7.13.0, cherry-pick :cherries:

#578 [RHPAM-4026] - [OpenShift] Users and Groups are not displayed in Admi…
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
  templates/rhpam713-authoring-ha.yaml
  templates/rhpam713-authoring.yaml
  templates/rhpam713-kieserver-externaldb.yaml
  templates/rhpam713-kieserver-mysql.yaml
  templates/rhpam713-kieserver-postgresql.yaml
  templates/rhpam713-managed.yaml
  templates/rhpam713-prod-immutable-kieserver-amq.yaml
  templates/rhpam713-prod-immutable-kieserver.yaml
  templates/rhpam713-prod-immutable-monitor.yaml
  templates/rhpam713-prod.yaml
  templates/rhpam713-trial-ephemeral.yaml
Labels: ready 🚀, main ⇨ 7.13.0, needs-cherry-pick :cherries:

#581 [RHPAM-4026] - [OpenShift] Users and Groups are not displayed in Admin perspective
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
  templates/rhpam712-authoring-ha.yaml
  templates/rhpam712-authoring.yaml
  templates/rhpam712-kieserver-externaldb.yaml
  templates/rhpam712-kieserver-mysql.yaml
  templates/rhpam712-kieserver-postgresql.yaml
  templates/rhpam712-managed.yaml
  templates/rhpam712-prod-immutable-kieserver-amq.yaml
  templates/rhpam712-prod-immutable-kieserver.yaml
  templates/rhpam712-prod-immutable-monitor.yaml
  templates/rhpam712-prod.yaml
  templates/rhpam712-trial-ephemeral.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.0, cherry-pick :cherries:

#584 docs review - capitalize all ldap occurrencies
  templates/rhpam713-authoring-ha.yaml
  templates/rhpam713-authoring.yaml
  templates/rhpam713-kieserver-externaldb.yaml
  templates/rhpam713-kieserver-mysql.yaml
  templates/rhpam713-kieserver-postgresql.yaml
  templates/rhpam713-managed.yaml
  templates/rhpam713-prod-immutable-kieserver-amq.yaml
  templates/rhpam713-prod-immutable-kieserver.yaml
  templates/rhpam713-prod-immutable-monitor.yaml
  templates/rhpam713-prod.yaml
  templates/rhpam713-trial-ephemeral.yaml
Labels: needs review :mag:, main ⇨ 7.13.0

#583 docs review - capitalize all ldap occurrencies
  templates/rhpam712-authoring-ha.yaml
  templates/rhpam712-authoring.yaml
  templates/rhpam712-kieserver-externaldb.yaml
  templates/rhpam712-kieserver-mysql.yaml
  templates/rhpam712-kieserver-postgresql.yaml
  templates/rhpam712-managed.yaml
  templates/rhpam712-prod-immutable-kieserver-amq.yaml
  templates/rhpam712-prod-immutable-kieserver.yaml
  templates/rhpam712-prod-immutable-monitor.yaml
  templates/rhpam712-prod.yaml
  templates/rhpam712-trial-ephemeral.yaml
Labels: 7.12.x ⇨ 7.12.0, needs review :mag:

#582 update templates's adoc
  templates/docs/rhpam712-authoring-ha.adoc
  templates/docs/rhpam712-authoring.adoc
  templates/docs/rhpam712-kieserver-externaldb.adoc
  templates/docs/rhpam712-kieserver-mysql.adoc
  templates/docs/rhpam712-kieserver-postgresql.adoc
  templates/docs/rhpam712-managed.adoc
  templates/docs/rhpam712-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam712-prod-immutable-kieserver.adoc
  templates/docs/rhpam712-prod-immutable-monitor.adoc
  templates/docs/rhpam712-prod.adoc
  templates/docs/rhpam712-trial-ephemeral.adoc
Labels: 7.12.x ⇨ 7.12.0, needs review :mag:

#585 update templates's adoc
  templates/docs/rhpam713-authoring-ha.adoc
  templates/docs/rhpam713-authoring.adoc
  templates/docs/rhpam713-kieserver-externaldb.adoc
  templates/docs/rhpam713-kieserver-mysql.adoc
  templates/docs/rhpam713-kieserver-postgresql.adoc
  templates/docs/rhpam713-managed.adoc
  templates/docs/rhpam713-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam713-prod-immutable-kieserver.adoc
  templates/docs/rhpam713-prod-immutable-monitor.adoc
  templates/docs/rhpam713-prod.adoc
  templates/docs/rhpam713-trial-ephemeral.adoc
Labels: needs review :mag:, main ⇨ 7.13.0

#587 fix small typo on ldap keep non mapped roles
  templates/rhpam713-authoring-ha.yaml
  templates/rhpam713-authoring.yaml
  templates/rhpam713-kieserver-externaldb.yaml
  templates/rhpam713-kieserver-mysql.yaml
  templates/rhpam713-kieserver-postgresql.yaml
  templates/rhpam713-managed.yaml
  templates/rhpam713-prod-immutable-kieserver-amq.yaml
  templates/rhpam713-prod-immutable-kieserver.yaml
  templates/rhpam713-prod-immutable-monitor.yaml
  templates/rhpam713-prod.yaml
  templates/rhpam713-trial-ephemeral.yaml
Labels: ready 🚀, main ⇨ 7.13.0, cherry-pick :cherries:

#586 fix small typo on ldap keep non mapped roles
  templates/rhpam712-authoring-ha.yaml
  templates/rhpam712-authoring.yaml
  templates/rhpam712-kieserver-externaldb.yaml
  templates/rhpam712-kieserver-mysql.yaml
  templates/rhpam712-kieserver-postgresql.yaml
  templates/rhpam712-managed.yaml
  templates/rhpam712-prod-immutable-kieserver-amq.yaml
  templates/rhpam712-prod-immutable-kieserver.yaml
  templates/rhpam712-prod-immutable-monitor.yaml
  templates/rhpam712-prod.yaml
  templates/rhpam712-trial-ephemeral.yaml
Labels: ready 🚀, main ⇨ 7.13.0, needs-cherry-pick :cherries:

#588 [KIECLOUD-610] - Provide a quickstart about how to add new users on E…
  quickstarts/post-configure-example/README.md
  quickstarts/post-configure-example/add-users.cli
  quickstarts/post-configure-example/delayedpostconfigure.sh
  quickstarts/post-configure-example/postconfigure.sh
Labels: ready 🚀, needs review :mag:, main ⇨ 7.13.0, needs-cherry-pick :cherries:

#590 [KIECLOUD-610] - Provide a quickstart about how to add new users on EAP
  quickstarts/post-configure-example/README.md
Labels: needs review :mag:

#589 [KIECLOUD-610] - Provide a quickstart about how to add new users on E…
  quickstarts/post-configure-example/README.md
  quickstarts/post-configure-example/add-users.cli
  quickstarts/post-configure-example/delayedpostconfigure.sh
  quickstarts/post-configure-example/postconfigure.sh
Labels: 7.12.x ⇨ 7.12.0, needs review :mag:, cherry-pick :cherries:

#591 [KIECLOUD-614] - Application Templates still referencing the AUTH_LDA…
  templates/rhpam712-authoring-ha.yaml
  templates/rhpam712-authoring.yaml
  templates/rhpam712-kieserver-externaldb.yaml
  templates/rhpam712-kieserver-mysql.yaml
  templates/rhpam712-kieserver-postgresql.yaml
  templates/rhpam712-managed.yaml
  templates/rhpam712-prod-immutable-kieserver-amq.yaml
  templates/rhpam712-prod-immutable-kieserver.yaml
  templates/rhpam712-prod-immutable-monitor.yaml
  templates/rhpam712-prod.yaml
  templates/rhpam712-trial-ephemeral.yaml
Labels: 7.12.x ⇨ 7.12.0, needs review :mag:, needs-cherry-pick :cherries:

#593 update adocs due KIECLOUD-614
  templates/docs/rhpam712-authoring-ha.adoc
  templates/docs/rhpam712-authoring.adoc
  templates/docs/rhpam712-kieserver-externaldb.adoc
  templates/docs/rhpam712-kieserver-mysql.adoc
  templates/docs/rhpam712-kieserver-postgresql.adoc
  templates/docs/rhpam712-managed.adoc
  templates/docs/rhpam712-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam712-prod-immutable-kieserver.adoc
  templates/docs/rhpam712-prod-immutable-monitor.adoc
  templates/docs/rhpam712-prod.adoc
  templates/docs/rhpam712-trial-ephemeral.adoc
Labels: 7.12.x ⇨ 7.12.0, needs review :mag:

#592 [KIECLOUD-614] - Application Templates still referencing the AUTH_LDA…
  templates/rhpam713-authoring-ha.yaml
  templates/rhpam713-authoring.yaml
  templates/rhpam713-kieserver-externaldb.yaml
  templates/rhpam713-kieserver-mysql.yaml
  templates/rhpam713-kieserver-postgresql.yaml
  templates/rhpam713-managed.yaml
  templates/rhpam713-prod-immutable-kieserver-amq.yaml
  templates/rhpam713-prod-immutable-kieserver.yaml
  templates/rhpam713-prod-immutable-monitor.yaml
  templates/rhpam713-prod.yaml
  templates/rhpam713-trial-ephemeral.yaml
Labels: needs review :mag:, main ⇨ 7.13.0, cherry-pick :cherries:
