Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2021-07, with the labels that each got.

#550 [RHPAM-3640] Configure Kafka JBPM Emitter from Operator -7.11.x
  kieserver/image.yaml
Labels: 7.11.x ⇨ 7.11.1, ready 🚀

#551 [RHPAM-3640] Configure Kafka JBPM Emitter from Operator
  kieserver/image.yaml
Labels: master ⇨ 7.12.0, ready 🚀

#552 [KIECLOUD-551] - Prepare RHPAM and RHDM for 7.11.1 release
  README.md
  businesscentral-monitoring/image.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/image.yaml
  businesscentral/tag-overrides.yaml
  controller/image.yaml
  controller/tag-overrides.yaml
  dashbuilder/image.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  process-migration/image.yaml
  process-migration/tag-overrides.yaml
  quickstarts/router-ext/README.md
  rhpam711-image-streams.yaml
  scripts/update-version.py
  smartrouter/image.yaml
  smartrouter/tag-overrides.yaml
  templates/contrib/jdbc/cekit/image.yaml
  templates/contrib/jdbc/cekit/modules/kie-custom-jdbc-driver/base-module.yaml
  templates/docs/rhpam711-authoring-ha.adoc
  templates/docs/rhpam711-authoring.adoc
  templates/docs/rhpam711-kieserver-externaldb.adoc
  templates/docs/rhpam711-kieserver-mysql.adoc
  templates/docs/rhpam711-kieserver-postgresql.adoc
  templates/docs/rhpam711-managed.adoc
  templates/docs/rhpam711-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam711-prod-immutable-kieserver.adoc
  templates/docs/rhpam711-prod-immutable-monitor.adoc
  templates/docs/rhpam711-prod.adoc
  templates/docs/rhpam711-trial-ephemeral.adoc
  templates/rhpam711-authoring-ha.yaml
  templates/rhpam711-authoring.yaml
  templates/rhpam711-kieserver-externaldb.yaml
  templates/rhpam711-kieserver-mysql.yaml
  templates/rhpam711-kieserver-postgresql.yaml
  templates/rhpam711-managed.yaml
  templates/rhpam711-prod-immutable-kieserver-amq.yaml
  templates/rhpam711-prod-immutable-kieserver.yaml
  templates/rhpam711-prod-immutable-monitor.yaml
  templates/rhpam711-prod.yaml
  templates/rhpam711-trial-ephemeral.yaml
Labels: 7.11.x ⇨ 7.11.1, needs review :mag:
