Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2021-06, with the labels that each got.

#543 [KIECLOUD-542] Conscious Language on KieCloud repos
  .circleci/config.yml
  README.md
  businesscentral-monitoring/README.adoc
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/image.yaml
  businesscentral/README.adoc
  businesscentral/branch-overrides.yaml
  businesscentral/image.yaml
  controller/README.adoc
  controller/branch-overrides.yaml
  controller/image.yaml
  dashbuilder/README.adoc
  dashbuilder/branch-overrides.yaml
  dashbuilder/image.yaml
  kieserver/README.adoc
  kieserver/branch-overrides.yaml
  kieserver/image.yaml
  process-migration/branch-overrides.yaml
  process-migration/image.yaml
  quickstarts/library-process/README.md
  quickstarts/router-ext/README.md
  scripts/generate-adocs.sh
  smartrouter/README.adoc
  smartrouter/branch-overrides.yaml
  smartrouter/image.yaml
  templates/README.md
  templates/contrib/jdbc/README.md
  templates/docs/README.adoc
  templates/docs/rhpam712-authoring-ha.adoc
  templates/docs/rhpam712-authoring.adoc
  templates/docs/rhpam712-kieserver-externaldb.adoc
  templates/docs/rhpam712-kieserver-postgresql.adoc
  templates/docs/rhpam712-managed.adoc
  templates/docs/rhpam712-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam712-prod-immutable-kieserver.adoc
  templates/docs/rhpam712-prod-immutable-monitor.adoc
  templates/docs/rhpam712-prod.adoc
  templates/docs/rhpam712-trial-ephemeral.adoc
  templates/rhpam712-prod-immutable-kieserver-amq.yaml
  templates/rhpam712-prod-immutable-kieserver.yaml
Labels: master ⇨ 7.12.0, ready 🚀

#544 [KIECLOUD-275] - Remove database related tags from templates
  templates/rhpam712-kieserver-mysql.yaml
  templates/rhpam712-kieserver-postgresql.yaml
  templates/rhpam712-managed.yaml
  templates/rhpam712-trial-ephemeral.yaml
Labels: master ⇨ 7.12.0, ready 🚀

#541 [KIECLOUD-532] JDBC driver on RHDM/RHPAM images
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
Labels: master ⇨ 7.12.0, ready 🚀

#549 [KIECLOUD-542] Conscious Language on KieCloud repos 7.11.x
  .circleci/config.yml
Labels: ready 🚀

#547 [KIECLOUD-532] JDBC driver on RHDM/RHPAM images (#541)
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
Labels: 7.11.x ⇨ 7.11.1, ready 🚀
