Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2021-11, with the labels that each got.

#567 [KIECLOUD-544] - Combine the prometheus agent and config modules
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
Labels: needs review :mag:, main ⇨ 7.13.0

#570 [RHPAM-4019] - BC HA not started in OpenShift because of datagrid rea…
  templates/rhpam712-authoring-ha.yaml
Labels: 7.12.x ⇨ 7.12.0, needs review :mag:

#571 [RHPAM-4019] - BC HA not started in OpenShift because of datagrid rea…
  templates/rhpam713-authoring-ha.yaml
Labels: needs review :mag:, main ⇨ 7.13.0

#566 [KIECLOUD-594] Migrate the access_log_valve script to wildfly-cekit-modules
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
Labels: needs review :mag:, main ⇨ 7.13.0

#575 [KIECLOUD-578]
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  dashbuilder/branch-overrides.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.0

#576 [KIECLOUD-578] Upgrade wildfly-cekit-modules to include Keycloak support for SSO 7.5
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  dashbuilder/branch-overrides.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
Labels: ready 🚀, main ⇨ 7.13.0

#569 [KIECLOUD-505] Update https.sh script to use the one provided by wildfly-cekit-modules
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
Labels: ready 🚀, main ⇨ 7.13.0
