Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2021-03, with the labels that each got.

#504 [RHPAM-3181] Update the openshift.PING to kubernetes.PING
  templates/rhpam711-authoring-ha.yaml
  templates/rhpam711-kieserver-externaldb.yaml
  templates/rhpam711-kieserver-mysql.yaml
  templates/rhpam711-kieserver-postgresql.yaml
  templates/rhpam711-managed.yaml
  templates/rhpam711-prod-immutable-kieserver-amq.yaml
  templates/rhpam711-prod-immutable-kieserver.yaml
  templates/rhpam711-prod-immutable-monitor.yaml
  templates/rhpam711-prod.yaml
Labels: master ⇨ 7.11.0, needs review :mag:, on hold ⏳

#519 [RHPAM-3494] - Make pulling of dependencies and kjar validation skipp…
  kieserver/image.yaml
Labels: master ⇨ 7.11.0, ready 🚀

#520 [RHPAM-3494] - Make pulling of dependencies and kjar validation skipp…
  kieserver/image.yaml
Labels: 7.10.x ⇨ 7.10.1, needs review :mag:

#521 [RHPAM - 3499] - [ONE-OFF](7.9.1) Make pulling of dependencies and kjar validation skippable in kie-server lauch script
  kieserver/image.yaml
Labels: 7.9.x ⇨ 7.9.1, ready 🚀

#522 [RHPAM-3506] - /opt/eap/bin/launch/messaging.sh No such file or direc…
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
Labels: master ⇨ 7.11.0, ready 🚀

#523 [KIECLOUD-508] - Prepare RHDM and RHPAM 7.10.x branches for 7.10.1 re…
  businesscentral-monitoring/README.adoc
  businesscentral-monitoring/image.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/image.yaml
  businesscentral/tag-overrides.yaml
  controller/README.adoc
  controller/image.yaml
  controller/tag-overrides.yaml
  dashbuilder/README.adoc
  dashbuilder/image.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/README.adoc
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  process-migration/image.yaml
  process-migration/tag-overrides.yaml
  quickstarts/library-process/pom.xml
  quickstarts/router-ext/README.md
  quickstarts/router-ext/pom.xml
  rhpam710-image-streams.yaml
  smartrouter/README.adoc
  smartrouter/image.yaml
  smartrouter/tag-overrides.yaml
  templates/contrib/jdbc/cekit/image.yaml
  templates/contrib/jdbc/cekit/modules/kie-custom-jdbc-driver/base-module.yaml
  templates/docs/rhpam710-authoring-ha.adoc
  templates/docs/rhpam710-authoring.adoc
  templates/docs/rhpam710-kieserver-externaldb.adoc
  templates/docs/rhpam710-kieserver-mysql.adoc
  templates/docs/rhpam710-kieserver-postgresql.adoc
  templates/docs/rhpam710-managed.adoc
  templates/docs/rhpam710-prod-immutable-kieserver-amq.adoc
  templates/docs/rhpam710-prod-immutable-kieserver.adoc
  templates/docs/rhpam710-prod-immutable-monitor.adoc
  templates/docs/rhpam710-prod.adoc
  templates/docs/rhpam710-trial-ephemeral.adoc
  templates/rhpam710-authoring-ha.yaml
  templates/rhpam710-authoring.yaml
  templates/rhpam710-kieserver-externaldb.yaml
  templates/rhpam710-kieserver-mysql.yaml
  templates/rhpam710-kieserver-postgresql.yaml
  templates/rhpam710-managed.yaml
  templates/rhpam710-prod-immutable-kieserver-amq.yaml
  templates/rhpam710-prod-immutable-kieserver.yaml
  templates/rhpam710-prod-immutable-monitor.yaml
  templates/rhpam710-prod.yaml
  templates/rhpam710-trial-ephemeral.yaml
Labels: 7.10.x ⇨ 7.10.1, needs review :mag:

#528 [KIECLOUD-509] - Update RHDM and RHPAM templates' description.
  templates/rhpam711-prod-immutable-monitor.yaml
Labels: master ⇨ 7.11.0, ready 🚀

#529 [KIECLOUD-516] - Update RHDM/RHPAM README files to match latest updates
  README.md
Labels: master ⇨ 7.11.0, needs review :mag:

#527 [RHPAM-3527] - Update EAP version from 7.3.6 on PAM 7.11.x
  businesscentral-monitoring/artifact-overrides.yaml
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/artifact-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/artifact-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  dashbuilder/artifact-overrides.yaml
  dashbuilder/branch-overrides.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/artifact-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  quickstarts/library-process/pom.xml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: master ⇨ 7.11.0, ready 🚀

#530 [KIECLOUD-518] - Update RHSSO EAP adatpers from 7.3.1 to 7.4.5
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
Labels: master ⇨ 7.11.0, ready 🚀

#531 [KIECLOUD-519] - Failing KIE JDBC Driver Extension Images builds with…
  templates/contrib/jdbc/cekit/Makefile
  templates/contrib/jdbc/cekit/README.md
  templates/contrib/jdbc/cekit/modules/kie-custom-jdbc-driver/install.sh
  templates/contrib/jdbc/cekit/prepare.sh
Labels: master ⇨ 7.11.0, ready 🚀

#526 [RHPAM-3330] Operator/Image support for Kie-Server Cluster support
  kieserver/image.yaml
Labels: master ⇨ 7.11.0, ready 🚀

#524 [RHPAM-3331] Operator for AMQ Streams (Kafka) integration
  kieserver/image.yaml
Labels: master ⇨ 7.11.0, ready 🚀
