Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2022-12, with the labels that each got.

#654 [RHPAM-3709] - CVE-2021-26291 rhpam-7-businesscentral-rhel8-container…
  .gitignore
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/image.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/image.yaml
  businesscentral/tag-overrides.yaml
  controller/branch-overrides.yaml
  controller/image.yaml
  controller/tag-overrides.yaml
  dashbuilder/branch-overrides.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  process-migration/branch-overrides.yaml
  process-migration/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: cherry-pick :cherries:

#653 [RHPAM-3709] - CVE-2021-26291 rhpam-7-businesscentral-rhel8-container…
  .gitignore
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/image.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/image.yaml
  businesscentral/tag-overrides.yaml
  controller/branch-overrides.yaml
  controller/image.yaml
  controller/tag-overrides.yaml
  dashbuilder/branch-overrides.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  process-migration/branch-overrides.yaml
  process-migration/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: cherry-pick :cherries:, 7.13.x ⇨ 7.13.2

#647 [RHPAM-4147] - baseFilter(AUTH_LDAP_BASE_FILTER) is incompatible with…
  templates/decision/rhdm714-authoring-ha.yaml
  templates/decision/rhdm714-authoring.yaml
  templates/decision/rhdm714-kieserver.yaml
  templates/decision/rhdm714-prod-immutable-kieserver-amq.yaml
  templates/decision/rhdm714-prod-immutable-kieserver.yaml
  templates/decision/rhdm714-trial-ephemeral.yaml
  templates/process/rhpam714-authoring-ha.yaml
  templates/process/rhpam714-authoring.yaml
  templates/process/rhpam714-kieserver-externaldb.yaml
  templates/process/rhpam714-kieserver-mysql.yaml
  templates/process/rhpam714-kieserver-postgresql.yaml
  templates/process/rhpam714-managed.yaml
  templates/process/rhpam714-prod-immutable-kieserver-amq.yaml
  templates/process/rhpam714-prod-immutable-kieserver.yaml
  templates/process/rhpam714-prod-immutable-monitor.yaml
  templates/process/rhpam714-prod.yaml
  templates/process/rhpam714-trial-ephemeral.yaml
Labels: ready 🚀, main ⇨ 7.14.0

#648 [7.13.x][RHPAM-4147] - baseFilter(AUTH_LDAP_BASE_FILTER) is incompati…
  templates/decision/rhdm713-authoring-ha.yaml
  templates/decision/rhdm713-authoring.yaml
  templates/decision/rhdm713-kieserver.yaml
  templates/decision/rhdm713-prod-immutable-kieserver-amq.yaml
  templates/decision/rhdm713-prod-immutable-kieserver.yaml
  templates/decision/rhdm713-trial-ephemeral.yaml
  templates/docs/decision/rhdm713-authoring-ha.adoc
  templates/docs/decision/rhdm713-authoring.adoc
  templates/docs/decision/rhdm713-kieserver.adoc
  templates/docs/decision/rhdm713-prod-immutable-kieserver-amq.adoc
  templates/docs/decision/rhdm713-prod-immutable-kieserver.adoc
  templates/docs/decision/rhdm713-trial-ephemeral.adoc
  templates/docs/process/rhpam713-authoring-ha.adoc
  templates/docs/process/rhpam713-authoring.adoc
  templates/docs/process/rhpam713-kieserver-externaldb.adoc
  templates/docs/process/rhpam713-kieserver-mysql.adoc
  templates/docs/process/rhpam713-kieserver-postgresql.adoc
  templates/docs/process/rhpam713-managed.adoc
  templates/docs/process/rhpam713-prod-immutable-kieserver-amq.adoc
  templates/docs/process/rhpam713-prod-immutable-kieserver.adoc
  templates/docs/process/rhpam713-prod-immutable-monitor.adoc
  templates/docs/process/rhpam713-prod.adoc
  templates/docs/process/rhpam713-trial-ephemeral.adoc
  templates/process/rhpam713-authoring-ha.yaml
  templates/process/rhpam713-authoring.yaml
  templates/process/rhpam713-kieserver-externaldb.yaml
  templates/process/rhpam713-kieserver-mysql.yaml
  templates/process/rhpam713-kieserver-postgresql.yaml
  templates/process/rhpam713-managed.yaml
  templates/process/rhpam713-prod-immutable-kieserver-amq.yaml
  templates/process/rhpam713-prod-immutable-kieserver.yaml
  templates/process/rhpam713-prod-immutable-monitor.yaml
  templates/process/rhpam713-prod.yaml
  templates/process/rhpam713-trial-ephemeral.yaml
Labels: ready 🚀, 7.13.x ⇨ 7.13.2

#659 [RHPAM-4616] - Update EAP version to 7.4.8 on RHPAM/BAMOE Images
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  dashbuilder/branch-overrides.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: ready 🚀, cherry-pick :cherries:

#655 [KIECLOUD-656] - Prepare RHPAM branches for 7.13.2
  businesscentral-monitoring/image.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/image.yaml
  businesscentral/tag-overrides.yaml
  controller/image.yaml
  controller/tag-overrides.yaml
  dashbuilder/image.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  process-migration/image.yaml
  process-migration/tag-overrides.yaml
  quickstarts/router-ext/README.md
  rhpam713-image-streams.yaml
  smartrouter/image.yaml
  smartrouter/tag-overrides.yaml
Labels: needs review :mag:, 7.13.x ⇨ 7.13.2

#661 [7.13.x-blue][KIECLOUD-672] add pkg-update module
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
  process-migration/image.yaml
  smartrouter/image.yaml
Labels: ready 🚀

#660 [7.13.x][KIECLOUD-672] add pkg-update module
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
  process-migration/image.yaml
  smartrouter/image.yaml
Labels: ready 🚀, 7.13.x ⇨ 7.13.2

#662 [KIECLOUD-672] add pkg-update module
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
  process-migration/image.yaml
  smartrouter/image.yaml
Labels: ready 🚀, main ⇨ 7.14.0
