Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2022-03, with the labels that each got.

#604 [KIECLOUD-604] - Move RHDM templates and quickstarts to RHPAM repository
  .circleci/config.yml
  README.md
  templates/README.md
  templates/decision/rhdm713-authoring-ha.yaml
  templates/decision/rhdm713-authoring.yaml
  templates/decision/rhdm713-kieserver.yaml
  templates/decision/rhdm713-prod-immutable-kieserver-amq.yaml
  templates/decision/rhdm713-prod-immutable-kieserver.yaml
  templates/decision/rhdm713-trial-ephemeral.yaml
  templates/process/rhpam713-authoring-ha.yaml
  templates/process/rhpam713-authoring.yaml
  templates/process/rhpam713-kieserver-externaldb.yaml
  templates/process/rhpam713-kieserver-mysql.yaml
  templates/process/rhpam713-kieserver-postgresql.yaml
  templates/process/rhpam713-managed.yaml
  templates/process/rhpam713-prod-immutable-kieserver-amq.yaml
  templates/process/rhpam713-prod-immutable-kieserver.yaml
  templates/process/rhpam713-prod-immutable-monitor.yaml
  templates/process/rhpam713-prod.yaml
  templates/process/rhpam713-trial-ephemeral.yaml
Labels: needs review :mag:, main ⇨ 7.13.0

#610 [KIECLOUD-228] Hide ISPN logs
  businesscentral/image.yaml
Labels: ready 🚀, main ⇨ 7.13.0

#612 [RHPAM-3665] - Postconfigure.sh not executed as custom KieServer S2I …
  quickstarts/post-configure-example/README.md
  quickstarts/post-configure-example/delayedpostconfigure.sh
Labels: ready 🚀, main ⇨ 7.13.0

#611 [KIECLOUD-628] - Update rhdm quickstarts references on operator
  scripts/generate-adocs.sh
  templates/decision/rhdm713-prod-immutable-kieserver-amq.yaml
  templates/decision/rhdm713-prod-immutable-kieserver.yaml
  templates/docs/decision/rhdm713-prod-immutable-kieserver-amq.adoc
  templates/docs/decision/rhdm713-prod-immutable-kieserver.adoc
Labels: ready 🚀, main ⇨ 7.13.0

#607 [KIECLOUD-603] Create KIE Server configuration option for RHDM capaba…
  kieserver/image.yaml
  templates/decision/rhdm713-authoring-ha.yaml
  templates/decision/rhdm713-authoring.yaml
  templates/decision/rhdm713-kieserver.yaml
  templates/decision/rhdm713-prod-immutable-kieserver-amq.yaml
  templates/decision/rhdm713-prod-immutable-kieserver.yaml
  templates/decision/rhdm713-trial-ephemeral.yaml
Labels: ready 🚀, main ⇨ 7.13.0

#613 [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image
  kieserver/image.yaml
Labels: needs review :mag:, main ⇨ 7.13.0, needs-cherry-pick :cherries:

#614 [RHPAM-3528] Increase KieExecutorMDB threads in RHPAM image (#613)
  kieserver/image.yaml
Labels: main ⇨ 7.13.0

#616 [RHPAM-4194] - missing support of KIE_SERVER_BYPASS_AUTH_USER environ…
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
Labels: ready 🚀, main ⇨ 7.13.0

#618 [KIECLOUD-625] - Upgrade EAP to 7.4 latest cp patch on RHPAM images
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  dashbuilder/branch-overrides.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  process-migration/branch-overrides.yaml
  process-migration/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: ready 🚀, main ⇨ 7.13.0

#617 [KIECLOUD-627] 7.13 Checkpoint - Increase JDG version to 8.3.3
  templates/decision/rhdm713-authoring-ha.yaml
  templates/docs/decision/rhdm713-authoring-ha.adoc
  templates/docs/process/rhpam713-authoring-ha.adoc
  templates/process/rhpam713-authoring-ha.yaml
Labels: needs review :mag:, main ⇨ 7.13.0

#619 [KIECLOUD-626] - 7.13.0 Checkpoint - Increase AMQ broker version to 7…
  templates/decision/rhdm713-authoring-ha.yaml
  templates/process/rhpam713-authoring-ha.yaml
Labels: needs review :mag:, main ⇨ 7.13.0
