Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2022-01, with the labels that each got.

#596 [KIECLOUD-610] Fixing formatting issue with bash code in post-configure-example quic…
  quickstarts/post-configure-example/README.md
Labels: needs review :mag:, main ⇨ 7.13.0, needs-cherry-pick :cherries:

#597 [KIECLOUD-610] - Fixing formatting issue with bash code in post-configure-example quic…
  quickstarts/post-configure-example/README.md
Labels: ready 🚀, 7.12.x ⇨ 7.12.0, cherry-pick :cherries:

#595 RHPAM-4109 Cannot open created project - FileSystem Index fails - NullPointerException
  templates/rhpam713-authoring-ha.yaml
Labels: ready 🚀, main ⇨ 7.13.0, cherry-pick :cherries:

#598 update templates' adoc
  templates/docs/rhpam712-authoring-ha.adoc
Labels: ready 🚀, 7.12.x ⇨ 7.12.0

#599 Updated Reviewers file to include davidesalerno
  .github/bot-files/reviewers.yml
Labels: needs review :mag:

#572 [KIECLOUD-594] 7.12.x Migrate the access_log_valve script to wildfly-cekit-modules
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.1

#568 [KIECLOUD-544] - Combine the prometheus agent and config modules
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.1

#577 [KIECLOUD-505] 7.12.x Update https.sh script to use the one provided by wildfly-cekit-modules
  businesscentral-monitoring/image.yaml
  businesscentral/image.yaml
  controller/image.yaml
  dashbuilder/image.yaml
  kieserver/image.yaml
Labels: ready 🚀, 7.12.x ⇨ 7.12.1
