Repository jboss-container-images/rhpam-7-openshift-image, pull requests merged in 2022-08, with the labels that each got.

#634 [RHPAM-4439] Vulnerable Version Of PostgreSQL Found
  templates/process/rhpam713-kieserver-postgresql.yaml
Labels: ready 🚀, release-7.13.1

#633 [RHPAM-4439] Vulnerable Version Of PostgreSQL Found
  templates/process/rhpam714-kieserver-postgresql.yaml
Labels: ready 🚀

#638 [RHPAM-4481] - Update EAP version to 7.4.6 on RHPAM Images
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  dashbuilder/branch-overrides.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: ready 🚀, needs-cherry-pick :cherries:

#639 [RHPAM-4481] - Update EAP version to 7.4.6 on RHPAM Images
  businesscentral-monitoring/branch-overrides.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/branch-overrides.yaml
  businesscentral/tag-overrides.yaml
  controller/branch-overrides.yaml
  controller/tag-overrides.yaml
  dashbuilder/branch-overrides.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/branch-overrides.yaml
  kieserver/tag-overrides.yaml
  smartrouter/branch-overrides.yaml
  smartrouter/tag-overrides.yaml
Labels: ready 🚀, cherry-pick :cherries:

#641 [KIECLOUD-653] - Update 7.13.x-blue branch for 8.0.1 release
  businesscentral-monitoring/image.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/image.yaml
  businesscentral/tag-overrides.yaml
  controller/image.yaml
  controller/tag-overrides.yaml
  dashbuilder/image.yaml
  dashbuilder/tag-overrides.yaml
  ibm-bamoe8-image-streams.yaml
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  process-migration/image.yaml
  process-migration/tag-overrides.yaml
  quickstarts/router-ext/README.md
  scripts/update-version.py
  smartrouter/image.yaml
  smartrouter/tag-overrides.yaml
Labels: needs review :mag:

#642 [KIECLOUD-653] - Update 7.13.x branch for 7.13.1 release
  businesscentral-monitoring/image.yaml
  businesscentral-monitoring/tag-overrides.yaml
  businesscentral/image.yaml
  businesscentral/tag-overrides.yaml
  controller/image.yaml
  controller/tag-overrides.yaml
  dashbuilder/image.yaml
  dashbuilder/tag-overrides.yaml
  kieserver/image.yaml
  kieserver/tag-overrides.yaml
  process-migration/image.yaml
  process-migration/tag-overrides.yaml
  quickstarts/router-ext/README.md
  rhpam713-image-streams.yaml
  smartrouter/image.yaml
  smartrouter/tag-overrides.yaml
Labels: needs review :mag:, release-7.13.1
